### ISSUE TITLE
Issue: psutil is preventing me from downloading mljar-mercury package

### ISSUE THREAD

**Issue by ConnorBarr23** [mljar/mercury#202]
**Hi there,**
**I've been trying for a few weeks now to deploy my first Mercury app. At first, the Python gevent package was preventing the download. I eventually realized that the current version of gevent wasn't compatible with my 3.11 version of Python, so I downgraded to 3.10 and got through that issue. Now, the Python package psutil is preventing my download of mljar-mercury package.**

**The strange thing is that I was able to download the psutil package no problem:**
![image](https://user-images.githubusercontent.com/122316586/217374186-54153976-ff3b-4453-971c-8029fb1137ae.png)

**But then, when I try to download mercury, it throws up an error and blames the psutil package, which I previously downloaded:**
![image](https://user-images.githubusercontent.com/122316586/217374407-3308b8da-cb09-4e2e-9435-3aa9358882e4.png)

**Here is the full error message:**

Building wheels for collected packages: psutil
  Building wheel for psutil (setup.py): started
  Building wheel for psutil (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  python setup.py bdist_wheel did not run successfully.
  exit code: 1

  [46 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-310
  creating build\lib.win-amd64-cpython-310\psutil
  copying psutil\_common.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_compat.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_psaix.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_psbsd.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_pslinux.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_psosx.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_psposix.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_pssunos.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_pswindows.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\__init__.py -> build\lib.win-amd64-cpython-310\psutil
  creating build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\runner.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_aix.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_bsd.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_connections.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_contracts.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_linux.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_misc.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_osx.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_posix.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_process.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_sunos.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_system.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_testutils.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_unicode.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_windows.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\__init__.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\__main__.py -> build\lib.win-amd64-cpython-310\psutil\tests
  running build_ext
  building 'psutil._psutil_windows' extension
  creating build\temp.win-amd64-cpython-310
  creating build\temp.win-amd64-cpython-310\Release
  creating build\temp.win-amd64-cpython-310\Release\psutil
  creating build\temp.win-amd64-cpython-310\Release\psutil\arch
  creating build\temp.win-amd64-cpython-310\Release\psutil\arch\windows
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=580 -DPSUTIL_WINDOWS=1 -D_WIN32_WINNT=0x01000 -D_AVAIL_WINVER_=0x01000 -D_CRT_SECURE_NO_WARNINGS -DPSAPI_VERSION=1 -IC:\Users\connor.barr\HighRiseWindLoadingApp\venv\include -IC:\Users\connor.barr\AppData\Local\Programs\Python\Python310\include -IC:\Users\connor.barr\AppData\Local\Programs\Python\Python310\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /Tcpsutil/_psutil_common.c /Fobuild\temp.win-amd64-cpython-310\Release\psutil/_psutil_common.obj
  _psutil_common.c
  C:\Users\connor.barr\AppData\Local\Programs\Python\Python310\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psutil
  Running setup.py clean for psutil
Failed to build psutil
Installing collected packages: psutil, prompt-toolkit, platformdirs, parso, pandocfilters, packaging, nest-asyncio, matplotlib-inline, markupsafe, markdown, jupyterlab-pygments, importlib-metadata, idna, greenlet, entrypoints, defusedxml, decorator, debugpy, colorama, click, cffi, certifi, bleach, beautifulsoup4, attrs, asgiref, amqp, tqdm, sqlalchemy, requests, kombu, jupyter-core, jsonschema, jinja2, jedi, gevent, django, croniter, click-repl, click-plugins, click-didyoumean, pyppeteer, nbformat, jupyter-client, ipython, djangorestframework, django-storages, django-filter, django-cors-headers, celery, nbclient, ipykernel, django-drf-filepond, nbconvert, mljar-mercury
  Attempting uninstall: psutil
    Found existing installation: psutil 5.9.4
    Uninstalling psutil-5.9.4:
      Successfully uninstalled psutil-5.9.4
  Running setup.py install for psutil: started
  Running setup.py install for psutil: finished with status 'error'
  error: subprocess-exited-with-error

  Running setup.py install for psutil did not run successfully.
  exit code: 1

  [48 lines of output]
  running install
  C:\Users\connor.barr\HighRiseWindLoadingApp\venv\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    warnings.warn(
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-310
  creating build\lib.win-amd64-cpython-310\psutil
  copying psutil\_common.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_compat.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_psaix.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_psbsd.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_pslinux.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_psosx.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_psposix.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_pssunos.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\_pswindows.py -> build\lib.win-amd64-cpython-310\psutil
  copying psutil\__init__.py -> build\lib.win-amd64-cpython-310\psutil
  creating build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\runner.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_aix.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_bsd.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_connections.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_contracts.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_linux.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_memleaks.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_misc.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_osx.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_posix.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_process.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_sunos.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_system.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_testutils.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_unicode.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\test_windows.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\__init__.py -> build\lib.win-amd64-cpython-310\psutil\tests
  copying psutil\tests\__main__.py -> build\lib.win-amd64-cpython-310\psutil\tests
  running build_ext
  building 'psutil._psutil_windows' extension
  creating build\temp.win-amd64-cpython-310
  creating build\temp.win-amd64-cpython-310\Release
  creating build\temp.win-amd64-cpython-310\Release\psutil
  creating build\temp.win-amd64-cpython-310\Release\psutil\arch
  creating build\temp.win-amd64-cpython-310\Release\psutil\arch\windows
  "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=580 -DPSUTIL_WINDOWS=1 -D_WIN32_WINNT=0x01000 -D_AVAIL_WINVER_=0x01000 -D_CRT_SECURE_NO_WARNINGS -DPSAPI_VERSION=1 -IC:\Users\connor.barr\HighRiseWindLoadingApp\venv\include -IC:\Users\connor.barr\AppData\Local\Programs\Python\Python310\include -IC:\Users\connor.barr\AppData\Local\Programs\Python\Python310\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /Tcpsutil/_psutil_common.c /Fobuild\temp.win-amd64-cpython-310\Release\psutil/_psutil_common.obj
  _psutil_common.c
  C:\Users\connor.barr\AppData\Local\Programs\Python\Python310\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of psutil
  Moving to c:\users\connor.barr\highrisewindloadingapp\venv\lib\site-packages\psutil-5.9.4.dist-info\
   from C:\Users\connor.barr\HighRiseWindLoadingApp\venv\Lib\site-packages\~sutil-5.9.4.dist-info
  Moving to c:\users\connor.barr\highrisewindloadingapp\venv\lib\site-packages\psutil\
   from C:\Users\connor.barr\HighRiseWindLoadingApp\venv\Lib\site-packages\~sutil
error: legacy-install-failure

Encountered error while trying to install package.

psutil

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
(venv)

**Comment by pplonski** [comment]
Hi @ConnorBarr23,

Please try to install Python version 3.8 - not all packages might work with 3.11 or 3.10.

I'm working on Mercury V2 - after release I will take care of backlog and check this issue.

In Mercury V2 you will add widgets as Python code! The release should be this month :)

**Comment by ConnorBarr23** [comment]
Hi @pplonski ,

This worked! I uninstalled Python 3.10 and installed Python 3.8 instead and was able to download the mercury package. Thanks so much! 
I ran into a few other issues with the Heroku CLI - I had to update the PATH variables. But eventually, I was able to deploy my web app!

Thanks again. Looking forward to checking out Mercury V2 :)
