### ISSUE TITLE
mercury run demo error

### ISSUE THREAD

**Issue by DrHagva** [mljar/mercury#203]
Hello,
On Windows 10,  I have just installed mercury with conda, version 3.2.5 with
`conda install -c conda-forge mljar-mercury`

Following the Installation chapter from  the documentation, I tried
`mercury run demo`

I get the following issue:

> Traceback (most recent call last):
>   File "C:\Users\user\Anaconda3\envs\mercury\Scripts\mercury-script.py", line 9, in <module>
>     sys.exit(main())
>   File "C:\Users\user\Anaconda3\envs\mercury\lib\site-packages\mercury\mercury.py", line 56, in main
>     create_demo_notebook("demo.ipynb")
>   File "C:\Users\user\Anaconda3\envs\mercury\lib\site-packages\mercury\demo.py", line 38, in create_demo_notebook
>     nbf.write(nb, f)
>   File "C:\Users\user\Anaconda3\envs\mercury\lib\site-packages\nbformat\__init__.py", line 200, in write
>     fp.write(s)
>   File "C:\Users\user\Anaconda3\envs\mercury\lib\encodings\cp1252.py", line 19, in encode
>     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
> UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f680' in position 129: character maps to <undefined>

As a result demo.ipynb is created but empty.

This issue might be related to the following problem.
When trying the Get Started chapter from the documentation, the greeting exemple is not working. When trying to run the notebook, I get the following error:

> Notebook is executed with errors.
> Traceback (most recent call last): File "C:\Users\user\Anaconda3\envs\mercury\Scripts\jupyter-nbconvert-script.py", line 10, in <module> sys.exit(main()) File "C:\Users\user\Anaconda3\envs\mercury\lib\site-packages\jupyter_core\application.py", line 276, in launch_instance return super().launch_instance(argv=argv, **kwargs) File "C:\Users\user\Anaconda3\envs\mercury\lib\site-packages\traitlets\config\application.py", line 992, in launch_instance app.start() File "C:\Users\user\Anaconda3\envs\mercury\lib\site-packages\nbconvert\nbconvertapp.py", line 361, in start self.convert_notebooks() File "C:\Users\user\Anaconda3\envs\mercury\lib\site-packages\nbconvert\nbconvertapp.py", line 533, in convert_notebooks self.convert_single_notebook(notebook_filename) File "C:\Users\user\Anaconda3\envs\mercury\lib\site-packages\nbconvert\nbconvertapp.py", line 498, in convert_single_notebook output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer) File "C:\Users\user\Anaconda3\envs\mercury\lib\site-packages\nbconvert\nbconvertapp.py", line 427, in export_single_notebook output, resources = self.exporter.from_filename(notebook_filename, resources=resources) File "C:\Users\user\Anaconda3\envs\mercury\lib\site-packages\nbconvert\exporters\exporter.py", line 186, in from_filename return self.from_file(f, resources=resources, **kw) File "C:\Users\user\Anaconda3\envs\mercury\lib\site-packages\nbconvert\exporters\exporter.py", line 204, in from_file return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw) File "C:\Users\user\Anaconda3\envs\mercury\lib\site-packages\nbconvert\exporters\html.py", line 145, in from_notebook_node return super().from_notebook_node(nb, resources, **kw) File "C:\Users\user\Anaconda3\envs\mercury\lib\site-packages\nbconvert\exporters\templateexporter.py", line 392, in from_notebook_node output = self.template.render(nb=nb_copy, resources=resources) File "C:\Users\user\Anaconda3\envs\mercury\lib\site-packages\jinja2\environment.py", line 1301, in render self.environment.handle_exception() File "C:\Users\user\Anaconda3\envs\mercury\lib\site-packages\jinja2\environment.py", line 936, in handle_exception raise rewrite_traceback_stack(source=source) File "C:\Users\user\Anaconda3\envs\mercury\share\jupyter\nbconvert\templates\lab\index.html.j2", line 3, in top-level template code {% from 'jupyter_widgets.html.j2' import jupyter_widgets %} File "C:\Users\user\Anaconda3\envs\mercury\share\jupyter\nbconvert\templates\lab\base.html.j2", line 234, in top-level template code {% set div_id = uuid4() %} File "C:\Users\user\Anaconda3\envs\mercury\share\jupyter\nbconvert\templates\base\display_priority.j2", line 1, in top-level template code {%- extends 'base/null.j2' -%} File "C:\Users\user\Anaconda3\envs\mercury\share\jupyter\nbconvert\templates\base\null.j2", line 24, in top-level template code {%- block header -%} File "C:\Users\user\Anaconda3\envs\mercury\share\jupyter\nbconvert\templates\lab\index.html.j2", line 9, in block 'header' {%- block html_head -%} File "C:\Users\user\Anaconda3\envs\mercury\share\jupyter\nbconvert\templates\lab\index.html.j2", line 36, in block 'html_head' {% block notebook_css %} File "C:\Users\user\Anaconda3\envs\mercury\share\jupyter\nbconvert\templates\lab\index.html.j2", line 37, in block 'notebook_css' {{ resources.include_css("static/index.css") }} File "C:\Users\user\Anaconda3\envs\mercury\lib\site-packages\nbconvert\exporters\html.py", line 151, in resources_include_css return jinja2.Markup(code) AttributeError: module 'jinja2' has no attribute 'Markup'

I work with Python 3.9.16, and a "conda update --all" test informs that everything is up to date.

Thank you!

**Comment by pplonski** [comment]
Hi @DrHagva,

Thank you for reporting the issue. Sorry for problems. Looks like a bug.

Are you able to run Mercury with your notebooks?

I'm currently working on Mercury V2. It should be available soon. It is completely different than V1. Widgets are added with Python code. The notebook execution speed is ~ x20 faster. I will look at this bug after V2 release. You can try V2 version by running `pip install mercury`. The documentation is in progress. You can check it on [RunMercury.com](https://runmercury.com). You can try Mercury V2 demo by executing `mercury run demo` - maybe it will work. But hard to say ...

**Comment by DrHagva** [comment]
Hi @pplonski ,
Thank you for your answer.
Mercury V2 works fine, thank you!
